### ISSUE TITLE
En "pessant" is described wrongly in the readme.

### ISSUE THREAD

**Issue by Ezbob** [SneManden/Chess.ts#1]
It's called "en passant" (french for "In passing") and refers to the move wherein a pawn that makes a long move from the starting position can be captured by a opposing pawn by capturing the space right behind the moved pawn. It's a special move like "castling".
Wiki has nice animations:
https://en.wikipedia.org/wiki/En_passant  

Promotion is what you are describing in readme under en passant.

**Comment by SneManden** [comment]
Thank you, ahh yes, I got confused between the two terms initially and forgot to update the readme.
I didn’t know about the en passant move before I checked up on the rules for my implementation... 
Again, thank you for reminding me!

**Comment by SneManden** [comment]
Fixed.
